import
  ./test_bin_trie,
  ./test_binaries_utils,
  ./test_branches_utils,
  ./test_examples,
  ./test_hexary_trie,
  ./test_json_suite,
  ./test_sparse_binary_trie,
  ./test_transaction_db,
  ./test_trie_bitseq
